import os
from pathlib import Path
import zipfile
from collections import defaultdict

# ----------------------------
# CONFIGURATION
# ----------------------------

ROOT_DIR = Path("/home/adrien/SPombe_MatRegion_Model/March2026/diffusive")  
OUTPUT_ZIP = "FigS7.zip"
README_NAME = "README.md"

# allowed LAMMPS-related extensions / files
ALLOWED_EXTENSIONS = {
    ".template",
    ".lammpstrj",
    ".dat",
    ".map",
    ".txt",
    ".equil"
}

SPECIAL_FILES = {
    "input.lammps"
}

# files to ALWAYS skip
EXCLUDE_FILES = {
    "log.lammps",
    "output.log"
}
# ----------------------------
# DETERMINE SCAN MODE
# ----------------------------

subdirs = [p for p in ROOT_DIR.iterdir() if p.is_dir()]

# If subfolders exist → ONLY scan them
# If none exist → scan root itself
if subdirs:
    scan_roots = subdirs
    base_for_zip = ROOT_DIR 
else:
    scan_roots = [ROOT_DIR]
    base_for_zip = ROOT_DIR 
    
# ----------------------------
# COLLECT FILES
# ----------------------------

selected_files = []
folder_set = set()
file_type_counter = defaultdict(int)

for file_path in ROOT_DIR.rglob("*"):
    if file_path.is_file():
        name = file_path.name.lower()
        ext = file_path.suffix.lower()

        # skip large logs
        if name in EXCLUDE_FILES:
            continue

        # match allowed types
        if ext in ALLOWED_EXTENSIONS or file_path.name in SPECIAL_FILES:
            selected_files.append(file_path)
            folder_set.add(file_path.parent)

            file_type_counter[ext if ext else file_path.name] += 1

# ----------------------------
# CREATE ZIP
# ----------------------------

with zipfile.ZipFile(OUTPUT_ZIP, "w", zipfile.ZIP_DEFLATED) as zipf:
    for file_path in selected_files:
        arcname = file_path.relative_to(base_for_zip)
        zipf.write(file_path, arcname)

# ----------------------------
# CREATE README
# ----------------------------

sorted_folders = sorted(str(p.relative_to(ROOT_DIR)) for p in folder_set)

readme_lines = []

readme_lines.append("# LAMMPS Data Package\n")
readme_lines.append("Data generated by a modified LAMMPS version (from stable April 2024 version) for the Berard et al. paper: Epigenetic memory achieved through chromatin-induced phase separation.\n")

readme_lines.append("## Summary\n")
readme_lines.append(f"- Total folders: {len(folder_set)}")
readme_lines.append(f"- Total files included: {len(selected_files)}\n")

readme_lines.append("## Folder structure\n")
for f in sorted_folders:
    readme_lines.append(f"- {f}")

readme_lines.append("\n## File types included\n")
for k, v in sorted(file_type_counter.items()):
    readme_lines.append(f"- {k}: {v} files")

readme_lines.append("\n## Notes\n")
readme_lines.append("- Excluded large logs: log.lammps, output.log")
readme_lines.append("- Only LAMMPS-related input and data files were packaged")

readme_content = "\n".join(readme_lines)

# write README into zip
with zipfile.ZipFile(OUTPUT_ZIP, "a", zipfile.ZIP_DEFLATED) as zipf:
    zipf.writestr(README_NAME, readme_content)

print(f"Created: {OUTPUT_ZIP}")
print(f"Included {len(selected_files)} files from {len(folder_set)} folders")